WebRails/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :activities
  post 'generate/:id' => 'users#generate', as: :generate
  post 'disable/:id' => 'users#disable', as: :disable
  mount Forem::Engine, :at => '/forums'

  devise_for :users, :path_names => { :sign_up => "register" }

  root 'home#index'

  resources :profiles do
    get 'page/:page', :action => :index, :on => :collection
    get 'page/:page', :action => :index, :on => :collection
  end
  get  'profiles/:id'  => 'profiles#id',   as: :user
  post 'profiles/sync' => 'profiles#sync', as: :sync

  resources :school_modules
  post 'school_modules/unregister/:school_module_id/:username' => 'school_modules#unregister', as: :school_module_unregister
  post 'school_modules/register/:school_module_id/:username'   => 'school_modules#register',   as: :school_module_register

  resources :activities
  post 'activities/unregister/:activity_id/:username' => 'activities#unregister', as: :activity_unregister
  post 'activities/register/:activity_id/:username'   => 'activities#register',   as: :activity_register

  resources :tickets

  patch 'change_locale/:new_locale' => 'application#change_locale', as: :change_locale

end

WebRails/app/models/school_module.rb
class SchoolModule < ActiveRecord::Base
  serialize :users, Array
  before_save :create_forum
  validates :name, :presence => true, :length => { minimum: 3, maximum: 32 }
  validates :start, :presence => true
  validates :end, :presence => true
  validates :registration_start, :presence => true
  validates :registration_end, :presence => true

  def register(username)
    self.users << username unless self.users.include?(username)
    self.save
    self
  end

  def unregister(username)
    self.users.delete_if { |u| u == username}
    self.save
    self
  end

  def create_forum
    unless Forem::Category.where(name: self.name).first
      f = Forem::Category.new(name: self.name)
      f.save
      self.forum_category_id = f.id
    end
  end

  def forum_category
    Forem::Category.where(id: forum_category_id).first
  end
  alias :forem_category :forum_category
end

WebRails/app/controllers/school_modules_controller.rb
class SchoolModulesController < ApplicationController
  before_action :set_school_module, only: [:show, :edit, :update, :destroy]

  def register
    school_module = SchoolModule.find(params[:school_module_id])
    school_module.register(params[:username])
    respond_to do |format|
      format.html {redirect_to :back}
    end
  end

  def unregister
    school_module = SchoolModule.find(params[:school_module_id])
    school_module.unregister(params[:username])
    respond_to do |format|
      format.html {redirect_to :back}
    end
  end

  def new
    @school_module = SchoolModule.new
  end

  def show() end
  def edit() end

  def index
    @school_modules = SchoolModule.all
  end

  # POST /school_modules
  # POST /school_modules.json
  def create
    @school_module = SchoolModule.new(school_module_params)

    respond_to do |format|
      if @school_module.save
        format.html { redirect_to @school_module, notice: 'School module was successfully created.' }
        format.json { render :show, status: :created, location: @school_module }
      else
        format.html { render :new }
        format.json { render json: @school_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_modules/1
  # PATCH/PUT /school_modules/1.json
  def update
    respond_to do |format|
      if @school_module.update(school_module_params)
        format.html { redirect_to @school_module, notice: 'School module was successfully updated.' }
        format.json { render :show, status: :ok, location: @school_module }
      else
        format.html { render :edit }
        format.json { render json: @school_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_modules/1
  # DELETE /school_modules/1.json
  def destroy
    @school_module.destroy
    respond_to do |format|
      format.html { redirect_to school_modules_url, notice: 'School module was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_module
      @school_module = SchoolModule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_module_params
      params.require(:school_module).permit(:start, :end, :registration_start, :registration_end, :name, :description, users:[])
    end
end

WebRails/app/helpers/school_modules_helper.rb
module SchoolModulesHelper
end

WebRails/app/views/school_modules/_form.html.erb
<%= simple_form_for(@school_module) do |f| %>
  <% if @school_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school_module.errors.count, "error") %> prohibited this school_module from being saved:</h2>

      <ul>
      <% @school_module.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class='row collapse'>
  <div class='small-3 columns'>
    <h3>starting date</h3>
    <%= f.date_select :start %>
  </div>
  <div class='small-3 columns'>
    <h3>deadline</h3>
    <%= f.date_select :end %>
  </div>
  <div class='small-3 columns'>
    <h3>registrations</h3>
    <%= f.date_select :registration_start %>
  </div>
  <div class='small-3 columns'>
    <h3>registrations end</h3>
    <%= f.date_select :registration_end %>
  </div>

</div>

<div class='row'>
  <div class='small-3 columns'>
    <h3>Name</h3>
    <%= f.text_field :name %>
  </div>
  <div class='small-9 columns'>
    <h3>Description</h3>
    <%= f.text_area :description %>
  </div>

  <%= f.input :users, collection: User.all, as: :check_boxes %>

  <%= f.button :submit %>
</div>
<% end %>

WebRails/app/views/school_modules/edit.html.erb
<h1>Editing school_module</h1>

<%= render 'form' %>

<%= link_to 'Show', @school_module %> |
<%= link_to 'Back', school_modules_path %>

WebRails/app/views/school_modules/index.html.erb
<h1>Listing school_modules</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Registration start</th>
      <th>Registration end</th>
      <th>Users</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @school_modules.each do |school_module| %>
      <tr>
        <td><%= school_module.start %></td>
        <td><%= school_module.end %></td>
        <td><%= school_module.registration_start %></td>
        <td><%= school_module.registration_end %></td>
        <td><%= school_module.users %></td>
        <td><%= school_module.name %></td>
        <td><%= school_module.description %></td>
        <td><%= link_to 'Show', school_module %></td>
        <td><%= link_to 'Edit', edit_school_module_path(school_module) %></td>
        <td><%= link_to 'Destroy', school_module, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School module', new_school_module_path %>

WebRails/app/views/school_modules/new.html.erb
<h1>New school_module</h1>

<%= render 'form' %>

<%= link_to 'Back', school_modules_path %>

WebRails/app/views/school_modules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @school_module.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @school_module.end %>
</p>

<p>
  <strong>Registration start:</strong>
  <%= @school_module.registration_start %>
</p>

<p>
  <strong>Registration end:</strong>
  <%= @school_module.registration_end %>
</p>

<p>
  <strong>Users:</strong>
  <%= @school_module.users %>
</p>

<%= link_to 'Edit', edit_school_module_path(@school_module) %>
<%= link_to 'Back', school_modules_path %>
<%= link_to 'Register', school_module_register_url(@school_module, current_user), method: :post %>
<%= link_to 'Unregister', school_module_unregister_url(@school_module, current_user), method: :post %>