WebRails/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :activities
  post 'generate/:id' => 'users#generate', as: :generate
  post 'disable/:id' => 'users#disable', as: :disable
  mount Forem::Engine, :at => '/forums'

  devise_for :users, :path_names => { :sign_up => "register" }

  root 'home#index'

  resources :profiles do
    get 'page/:page', :action => :index, :on => :collection
    get 'page/:page', :action => :index, :on => :collection
  end
  get  'profiles/:id'  => 'profiles#id',   as: :user
  post 'profiles/sync' => 'profiles#sync', as: :sync

  resources :school_modules
  post 'school_modules/unregister/:school_module_id/:username' => 'school_modules#unregister', as: :school_module_unregister
  post 'school_modules/register/:school_module_id/:username'   => 'school_modules#register',   as: :school_module_register

  resources :activities
  post 'activities/unregister/:activity_id/:username' => 'activities#unregister', as: :activity_unregister
  post 'activities/register/:activity_id/:username'   => 'activities#register',   as: :activity_register

  resources :tickets

  patch 'change_locale/:new_locale' => 'application#change_locale', as: :change_locale

end

WebRails/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :assignee, class_name: 'User' #TODO
end

WebRails/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new
  end

  def show
    @ticket = Ticket.find params[:id]
  end

  def create
    Ticket.create(set_ticket_params)
    respond_to do |format|
      format.html {redirect_to :back}
    end
  end

  def set_ticket_params
    params.require(:ticket).permit(:title, :description, :priority, :fixed, :assignee, :submit)
  end
end

WebRails/app/helpers/tickets_helper.rb
module TicketsHelper
end

WebRails/app/views/tickets/index.html.haml
%h1 index.html.haml
= link_to t('ticket.new'), new_ticket_url, class: :button
- @tickets.each do |ticket|
  %row.collapse
    %h2= link_to ticket.title, ticket_url(ticket)
    %p= ticket.description

WebRails/app/views/tickets/new.html.haml
= simple_form_for @ticket do |f|
  %h1= @ticket.class.to_s
  = f.input :title
  = f.input :description
  = f.input :priority
  = f.input :fixed
  = f.association :assignee
  = f.button :submit

WebRails/app/views/tickets/show.html.haml
show.html.haml