WebRails/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :activities
  post 'generate/:id' => 'users#generate', as: :generate
  post 'disable/:id' => 'users#disable', as: :disable
  mount Forem::Engine, :at => '/forums'

  devise_for :users, :path_names => { :sign_up => "register" }

  root 'home#index'

  resources :profiles do
    get 'page/:page', :action => :index, :on => :collection
    get 'page/:page', :action => :index, :on => :collection
  end
  get  'profiles/:id'  => 'profiles#id',   as: :user
  post 'profiles/sync' => 'profiles#sync', as: :sync

  resources :school_modules
  post 'school_modules/unregister/:school_module_id/:username' => 'school_modules#unregister', as: :school_module_unregister
  post 'school_modules/register/:school_module_id/:username'   => 'school_modules#register',   as: :school_module_register

  resources :activities
  post 'activities/unregister/:activity_id/:username' => 'activities#unregister', as: :activity_unregister
  post 'activities/register/:activity_id/:username'   => 'activities#register',   as: :activity_register

  resources :tickets

  patch 'change_locale/:new_locale' => 'application#change_locale', as: :change_locale

end

WebRails/app/models/activity.rb
class Activity < ActiveRecord::Base
  serialize  :users, Array
  belongs_to :school_module
  before_save :create_forum
  # has_one :forum, class_name: 'Forem::Forum', foreign_key: 'forum_id'
  has_attached_file :learning_doc, :default_url => "/learning_doc_default.pdf"
  do_not_validate_attachment_file_type :learning_doc
  validates :school_module_id, :presence => true
  validates :name, :presence => true, :length => { minimum: 3, maximum: 32 }

  def register(username)
    self.users << username unless self.users.include?(username)
    self.save
    self
  end

  def unregister(username)
    self.users.delete_if { |u| u == username}
    self.save
    self
  end

  def create_forum
    unless Forem::Forum.where(name: self.name).first
      f = Forem::Forum.new(name: self.name,
                           category_id: self.school_module.forum_category.id,
                           description: self.description)
      f.save
      self.forum_id = f.id
    end
  end
  
  def title
    self.name
  end
end

WebRails/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def register
    activity = Activity.find(params[:activity_id])
    activity.register(params[:username])
    respond_to do |format|
      format.html {redirect_to :back}
    end
  end

  def unregister
    activity = Activity.find(params[:activity_id])
    activity.unregister(params[:username])
    respond_to do |format|
      format.html {redirect_to :back}
    end
  end

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
    respond_to do |format|
      format.html
      format.json { render json: @activities}
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @activity}
    end
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity  was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity  was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity  was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:start, :end, :registration_start, :registration_end, :name, :description, :school_module_id, :learning_doc, users:[])
    end
end

WebRails/app/helpers/activities_helper.rb
module ActivitiesHelper
end

WebRails/app/views/activities/_form.html.erb
<%= simple_form_for(@activity, html: {multipart: true}) do |f| %>
  <% if @activity.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@activity.errors.count, "error") %> prohibited thisactivity from being saved:</h3>

    <ul>
      <% @activity.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.file_field :learning_doc %>

  <div class='row collapse'>
    <div class='small-3 columns'>
      <h3>starting date</h3>
      <%= f.date_select :start %>
    </div>
    <div class='small-3 columns'>
      <h3>deadline</h3>
      <%= f.date_select :end %>
    </div>
    <div class='small-3 columns'>
      <h3>registrations</h3>
      <%= f.date_select :registration_start %>
    </div>
    <div class='small-3 columns'>
      <h3>registrations end</h3>
      <%= f.date_select :registration_end %>
    </div>

  </div>

  <div class='row'>
    <div class='small-3 columns'>
      <h3>Name</h3>
      <%= f.text_field :name %>
    </div>
    <div class='small-9 columns'>
      <h3>Description</h3>
      <%= f.text_area :description %>
    </div>
    <%= f.association :school_module %>

    <%= f.input :users, collection: User.all, as: :check_boxes %>

    <%= f.button :submit %>
  </div>
<% end %>

WebRails/app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

WebRails/app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Registration start</th>
      <th>Registration end</th>
      <th>Users</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.start %></td>
        <td><%= activity.end %></td>
        <td><%= activity.registration_start %></td>
        <td><%= activity.registration_end %></td>
        <td><%= activity.users %></td>
        <td><%= activity.name %></td>
        <td><%= activity.description %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

WebRails/app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

WebRails/app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to_if @activity.learning_doc, t('activity.pdf_download'), @activity.learning_doc.url %>

<p>
  <strong>Start:</strong>
  <%= @activity.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @activity.end %>
</p>

<p>
  <strong>Registration start:</strong>
  <%= @activity.registration_start %>
</p>

<p>
  <strong>Registration end:</strong>
  <%= @activity.registration_end %>
</p>

<p>
  <strong>Users:</strong>
  <%= @activity.users %>
</p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %>
<%= link_to 'Back', activities_path %>
<%= link_to 'Register', activity_register_url(@activity.id, current_user), method: :post %>
<%= link_to 'Unregister', activity_unregister_url(@activity.id, current_user), method: :post %>