WebRails/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :activities
  post 'generate/:id' => 'users#generate', as: :generate
  post 'disable/:id' => 'users#disable', as: :disable
  mount Forem::Engine, :at => '/forums'

  devise_for :users, :path_names => { :sign_up => "register" }

  root 'home#index'

  resources :profiles do
    get 'page/:page', :action => :index, :on => :collection
    get 'page/:page', :action => :index, :on => :collection
  end
  get  'profiles/:id'  => 'profiles#id',   as: :user
  post 'profiles/sync' => 'profiles#sync', as: :sync

  resources :school_modules
  post 'school_modules/unregister/:school_module_id/:username' => 'school_modules#unregister', as: :school_module_unregister
  post 'school_modules/register/:school_module_id/:username'   => 'school_modules#register',   as: :school_module_register

  resources :activities
  post 'activities/unregister/:activity_id/:username' => 'activities#unregister', as: :activity_unregister
  post 'activities/register/:activity_id/:username'   => 'activities#register',   as: :activity_register

  resources :tickets

  patch 'change_locale/:new_locale' => 'application#change_locale', as: :change_locale

end

WebRails/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @page = (params[:page] || 1).to_i
    sort_key = params[:sort_by] || :username
    @users = User.order(sort_key).page(@page).per(48)
  end

  def show
    @user = User.where(username: params[:id]).first
    unless @user
      flash[:alert] = t(:no_user_found)
      redirect_to root_path
    end
  end

  @@lock_sync = false

  def sync
    if !@@lock_sync
      Thread.new do
        @@lock_sync = true;
        User.sync
        @@lock_sync = false;
      end
    end
    @lock_sync = @@lock_sync
  end
end

WebRails/app/helpers/profiles_helper.rb
module ProfilesHelper
  def image_of(user)
    user[:picture] ? "data:image/jpg;base64,#{Base64.encode64(user[:picture])}" : "nopicture-profilview.png"
  end
end

WebRails/app/views/profiles/_user.html.haml
%li.columns
  = image_tag(image_of(@user), class: :'small-12')
  .class.panel
    %h5
      = link_to @user, profile_path(@user.username)
    %h6.subheader= @user[:'mobile-phone']

WebRails/app/views/profiles/index.html.haml
- button_class = :'button small-12 expand'
.row.collapse
  = paginate @users
  %dl.accordion(data-accordion)
    %dd.accordion-navigation
      %a(href="#panel1")= t 'ldap.accordion'
      #panel1.content
        %ul.small-block-grid-1.medium-block-grid-2.large-block-grid-3
          %li= link_to t('ldap.sync'), sync_url, method: :post, remote: true, class: button_class
          %li= link_to t('ldap.sort.username'), profiles_url('sort_by' => 'username'), remote: false, class: button_class
          %li= link_to t('ldap.sort.id'), profiles_url('sort_by' => 'id'), remote: false, class: button_class
          %li= link_to t('ldap.sort.uidnumber'), profiles_url('sort_by' => 'uidnumber'), remote: false, class: button_class
          %li= link_to t('ldap.sort.gidnumber'), profiles_url('sort_by' => 'gidnumber'), remote: false, class: button_class
          %li= link_to t('ldap.sort.cn'), profiles_url('sort_by' => 'cn'), remote: false, class: button_class

  .columns.small-12
    %ul.small-block-grid-2.medium-block-grid-4.large-block-grid-6
      - @users.each do |user|
        - @user = user
        = render partial: 'user'
  = paginate @users

WebRails/app/views/profiles/show.html.haml
- if current_user.id == @user.id
  = button_to 'Create autologin', generate_path(current_user.id)
  = button_to 'Disable autologin', disable_path(current_user.id)
.small-12.medium-3
  = image_tag(image_of(@user), class: :'small-12')
.small-12.medium-9
  .row.collapse
    %h2= @user.cn
    %h3= "#{@user.birth_date_time}"
  .row.collapse
    %h3=t 'profile.modules'
    %ul
      - @user.school_modules.each do |m|
        %li
          %h4= link_to m.name, school_module_url(m)
  .row.collapse
    %h3=t 'profile.activities'
    %ul
      - @user.activities.each do |m|
        %li
          %h4= link_to m.name, activity_url(m)